### ISSUE TITLE
Let's not show name in all uppercase

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-area51#17]
https://www.loom.com/share/220bc7c240ea4ffdb1c3f34be482a207

See the homepage of ActiveAdmin to see how they display the names at the top 

@Anamika-123 _a

**Comment by Anamika-123** [comment]
@neerajdotname Does this look fine?

<img width="1435" alt="Screenshot 2022-03-02 at 12 23 57 AM" src="https://user-images.githubusercontent.com/35066645/156231053-f6cb67c3-0b2f-4cc5-bf91-87394f3a1ca2.png">

**Comment by neerajdotname** [comment]
@Anamika-123 Looks much better. Let's roll with it.
