### ISSUE TITLE
Default sort and the ability to sort records

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-area51#20]
https://www.loom.com/share/02e866191860470e969b6b01bf6ee40b

**Comment by karthiknmenon** [comment]
@Thejus-Paul _a

**Comment by neerajdotname** [comment]
@AdityaBhutani _a

**Comment by neerajdotname** [comment]
Closing this issue. Will add the ability to order in which to sort along with bringing the model forward.
