### ISSUE TITLE
Ability to filter records

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-area51#27]
https://www.loom.com/share/9892111685d64ae4a93b686788490748

@PrateekArora03 _a

**Comment by neerajdotname** [comment]
@AdityaBhutani _a

**Comment by AdityaBhutani** [comment]
@neerajdotname While looking through [activeadmin](https://activeadmin.info/documentation.html) internals, realised it’s using [ransack](https://activerecord-hackery.github.io/ransack/getting-started/simple-mode) which seems a good option for us as well, for filtering. What are your thoughts on the same ?

**Comment by neerajdotname** [comment]
@AdityaBhutani I think we can use it. I don't see any point in rebuilding https://activerecord-hackery.github.io/ransack/getting-started/search-matches. 

If area51 uses it then it will be available for all the neeto products. I'm sure it shouldn't have any adverse impact anywhere.

@unnitallman any thoughts on this.

**Comment by AdityaBhutani** [comment]
@neerajdotname, About the UI, should we have a sidebar similar to activeadmin ?
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/21058509/161634449-7452e7ec-258a-4828-8282-8abe24f0fbb5.png">

**Comment by neerajdotname** [comment]
@AdityaBhutani Yup.

**Comment by unnitallman** [comment]
> @AdityaBhutani I think we can use it. I don't see any point in rebuilding https://activerecord-hackery.github.io/ransack/getting-started/search-matches.
> 
> If area51 uses it then it will be available for all the neeto products. I'm sure it shouldn't have any adverse impact anywhere.
> 
> @unnitallman any thoughts on this.

@AdityaBhutani Lets use ransack 👍
