### ISSUE TITLE
Updates navigation UI

### ISSUE THREAD

**Issue by shreyansh-g24** [bigbinary/neeto-area51#55]

**Comment by shreyansh-g24** [comment]
<img width="1792" alt="Screenshot 2022-04-15 at 12 47 56 PM" src="https://user-images.githubusercontent.com/40631571/163538238-09287021-c4af-4030-b3a2-48210a4e2cd2.png">

@karthiknmenon Please let me know your suggestions on UI for navigation Links in the bottom-left corner?

**Comment by karthiknmenon** [comment]
@shreyansh-g24 Let's use neetoUI sidebar with the following navLinks - 
1. area51
2. KPI Metrics
